# Generated by scripts/packagers.ts — do not edit by hand.
class Truo < Formula
  desc "TruoCloud CLI: VPS, DNS, databases, containers and load balancers"
  homepage "https://docs.truo.cloud/cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.3.0/truo-darwin-arm64"
      sha256 "7e8ca84d74be560765c2236ddc6b5be2a2c13ba44dc9264e04a922f5da8c6406"
    end
    on_intel do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.3.0/truo-darwin-x64"
      sha256 "6323fe440a75507cdb0ecd178cff32bc2d955eadd19bd4522aed09f04b378261"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.3.0/truo-linux-arm64"
      sha256 "dcaf307b5f9e56bba0e6d7e0b7f4f2b0050639a661275f7baed51a10a2a81d24"
    end
    on_intel do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.3.0/truo-linux-x64"
      sha256 "789a8d0667b80aac0afcca849ac49741367d1092b2c8504ba26448baeeb30370"
    end
  end

  def install
    bin.install Dir["truo-*"].first => "truo"
    generate_completions_from_executable(bin/"truo", "completion", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match "0.3.0", shell_output("#{bin}/truo --version")
  end
end
