# Generated by scripts/packagers.ts — do not edit by hand.
class Truo < Formula
  desc "TruoCloud CLI: VPS, DNS, databases, containers and load balancers"
  homepage "https://docs.truo.cloud/cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.4.0/truo-darwin-arm64"
      sha256 "5282dfe4f64e26d8777b8c363e6ac9ad6a267412939bbbb6a89f02ec48d1236e"
    end
    on_intel do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.4.0/truo-darwin-x64"
      sha256 "f2960b67610d856c8ea9f854b29cdcdcf0fff3397a92a4ea19f7294faeee5647"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.4.0/truo-linux-arm64"
      sha256 "4aa20add90dc1f822ef253502abaca822ea8b4c8c4dbfe7c134b3a53cfcabb10"
    end
    on_intel do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.4.0/truo-linux-x64"
      sha256 "0f44514f72b325599978fe6f7ee60cf595cb37b91d04c9c56d76500088183aea"
    end
  end

  def install
    bin.install Dir["truo-*"].first => "truo"
    generate_completions_from_executable(bin/"truo", "completion", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match "0.4.0", shell_output("#{bin}/truo --version")
  end
end
