# Generated by scripts/packagers.ts — do not edit by hand.
class Truo < Formula
  desc "TruoCloud CLI: VPS, DNS, databases, containers and load balancers"
  homepage "https://docs.truo.cloud/cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.2.0/truo-darwin-arm64"
      sha256 "350d201713a3adaa485ff4739045fbf20dd10bc435d6b72fdb5265a24d344597"
    end
    on_intel do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.2.0/truo-darwin-x64"
      sha256 "d1e77edb0892e3ad2e77532b70a6e54b05292f857c00304a20b35c81a87093da"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.2.0/truo-linux-arm64"
      sha256 "1bbe4e15ffc0d7297aa63b6b0bdd6330b22dc7c64764922656b9885da17ea82d"
    end
    on_intel do
      url "https://github.com/truocloud/truo-devkit/releases/download/v0.2.0/truo-linux-x64"
      sha256 "ad76915411456747a5b0233d78bcf9e55d191f019ffcb26a5b47bc088b9c584e"
    end
  end

  def install
    bin.install Dir["truo-*"].first => "truo"
    generate_completions_from_executable(bin/"truo", "completion", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match "0.2.0", shell_output("#{bin}/truo --version")
  end
end
